apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.91.241.10
    path: /storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.91.241.10
    path: "/storage/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
