---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
  name: php-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
      tier: backend
  template:
    metadata:
      labels:
        app: php-nginx
        tier: backend
    spec:
      volumes:
      - name: storage-claim
        emptyDir: {}
      - name: storage-data
        persistentVolumeClaim:
          claimName: data-storage-claim
      - name: config
        configMap:
          name: nginx-configmap
          items:
          - key: config
            path: site.conf
      initContainers:
        - name: my-app
          image: "bagrat92/php-nginx:v3"
          imagePullPolicy: IfNotPresent
          command: [ '/bin/sh', "-c", "cp -rp /apps  /storage"]
          volumeMounts:
            - name: storage-claim
              mountPath: /storage
      containers:
        -
          image: "ucraft/php-fpm:7.2"
          imagePullPolicy: IfNotPresent
          name: php
          ports:
          -
            containerPort: 9000
            protocol: TCP
          volumeMounts:
          - name: storage-claim
            mountPath: /storage
        -
          image: "nginx:1.7.9"
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
          -
            containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: storage-claim
            mountPath: /storage
          - name: config
            mountPath: /etc/nginx/conf.d

---
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: backend
  name: php-nginx
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: php-nginx
    tier: backend
  type: LoadBalancer
